# Generated by Django 5.2.1 on 2025-05-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sebze',
            name='type',
            field=models.CharField(default='Herhangi'),
        ),
    ]
