# Generated by Django 5.2.1 on 2025-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_sebze_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sebze',
            name='price',
            field=models.FloatField(default=1.0),
        ),
    ]
