# Generated by Django 5.2.1 on 2025-05-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_sebze_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sebze',
            name='shown_name',
            field=models.CharField(default='test'),
        ),
    ]
